//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by EVdance.rc
//
#define IDP_OLE_INIT_FAILED             100
#define IDD_ABOUTBOX                    101
#define IDB_WRITESMALL                  110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDR_MAINFRAME_256               129
#define IDR_EVdanceTYPE                 130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define IDR_PASTE_MENU                  151
#define IDR_WINDOWS_MENU                152
#define IDD_LINK_SETTINGS               153
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDR_RIBBON                      307
#define IDR_MAINFRAME                   308
#define IDR_UMLEDITYPE                  309
#define IDD_UML_DIALOG_PROPERTY_PACKAGE 310
#define IDD_UML_DIALOG_PROPERTY_LINK    311
#define IDR_UML_MENU_EDITOR_POPUP       312
#define IDD_UML_DIALOG_PROPERTY_NOTE    313
#define IDD_UML_DIALOG_PROPERTY_CLASS_ATTRIBUTE 314
#define IDI_UML_ICON_UP                 315
#define IDC_UML_CURSOR_DRAW             316
#define IDC_UML_CURSOR_ATTACH           317
#define IDC_UML_CURSOR_UP               318
#define IDD_UML_DIALOG_PROPERTY_CLASS   319
#define IDD_UML_DIALOG_PROPERTY_CLASS_OPERATION 320
#define IDD_UML_DIALOG_PROPERTY_CLASS_OPERATION_PARAMETER 321
#define IDR_UML_MENU_PACKAGE_POPUP      322
#define IDD_UML_DIALOG_PROPERTY_LABEL   323
#define IDD_UML_DIALOG_PROPERTY_INTERFACE 324
#define IDR_UML_MENU_CLASS_POPUP        325
#define IDD_UML_DIALOG_PROPERTY_EDITOR  326
#define IDR_UML_MENU_LINK               327
#define IDD_DIALOG_EXPORT               328
#define IDD_UML_DIALOG_PROPERTY_LIST_EDITOR 329
#define IDD_UML_DIALOG_PROPERTY_CLASS_DISPLAY 330
#define IDD_UML_DIALOG_GETTER_SETTER    331
#define IDD_UML_DIALOG_PROPERTY_TEMPLATE 332
#define IDD_UML_DIALOG_LINK_TITLE       333
#define IDC_CURSOR1                     335
#define IDC_UML_EDIT_LINK_TITLE         1000
#define IDC_RADIO_ACCESS                1003
#define IDC_RADIO5                      1004
#define IDC_RADIO6                      1005
#define IDC_EDIT_TEXT                   1006
#define IDC_EDIT_TYPE                   1007
#define IDC_BUTTON_FONT                 1008
#define IDC_BUTTON_COLOR                1009
#define IDC_RADIO_ASSOCIATION           1010
#define IDC_BUTTON_VISIBILITY           1010
#define IDC_CHECK_UNIDIRECTIONAL        1011
#define IDC_EDIT_START_LABEL            1012
#define IDC_EDIT_END_LABEL              1013
#define IDC_RADIO_DEPENDENCY            1014
#define IDC_RADIO_INHERITANCE           1015
#define IDC_RADIO_COMPOSITION           1016
#define IDC_EDIT_SECONDARY_START_LABEL  1017
#define IDC_EDIT_SECONDARY_END_LABEL    1018
#define IDC_LIST_ATTRIBUTES             1020
#define IDC_LIST_OPERATIONS             1021
#define IDC_BUTTON_ADD_ATTRIBUTE        1022
#define IDC_BUTTON_ADD_OPERATION        1024
#define IDC_EDIT_NAME                   1027
#define IDC_CHECK_ABSTRACT              1030
#define IDC_CHECK_STATIC                1031
#define IDC_LIST_PARAMETERS             1032
#define IDC_BUTTON_ADD                  1033
#define IDC_EDIT_MULTIPLICITY           1042
#define IDC_EDIT_INITIAL_VALUE          1043
#define IDC_EDIT_PROPERTY_LIST          1044
#define IDC_CHECK_CONST                 1048
#define IDC_RADIO_PARTOF                1051
#define IDC_CHECK_GRID                  1053
#define IDC_CHECK_SHOW_GRID             1054
#define IDC_CHECK_ONLY_PUBLIC           1055
#define IDC_CHECK_NO_MARKERS            1056
#define IDC_RADIO_INVISIBLE             1058
#define IDC_RADIO_HTML                  1059
#define IDC_RADIO_CPP                   1060
#define IDC_CHECK_STRIP_LEADING         1064
#define IDC_STATIC_STRIP_INFO           1065
#define IDC_CHECK_NO_ATTRIBUTES         1066
#define IDC_CHECK_NO_OPERATIONS         1067
#define IDC_CHECK_NO_ATTRIBUTE_NAMES    1069
#define IDC_LIST_TAGS                   1070
#define IDC_EDIT_VALUE                  1073
#define IDC_BUTTON_DELETE               1075
#define IDC_BUTTON_UPDATE               1076
#define IDC_BUTTON_PROPERTY_LIST        1076
#define IDC_BUTTON_AUTO_GENERATE        1079
#define IDC_CHECK_IN                    1080
#define IDC_BUTTON_AUTO_GENERATE2       1080
#define IDC_CHECK_OUT                   1081
#define IDC_CHECK_REFERENCE             1082
#define IDC_COMBO_STEREOTYPE            1083
#define IDC_COMBO_TAG                   1084
#define IDC_EDIT_GETTER                 1089
#define IDC_EDIT_SETTER                 1090
#define IDC_RADIO_EMF                   1091
#define IDC_CHECK_SHOW_MARGINS          1092
#define IDC_RADIO_INTERFACE             1093
#define IDC_BUTTON_CLOSE                1094
#define IDC_EDIT_PARAMETER              1096
#define IDC_CHECK_ONLY_H                1097
#define IDC_EDIT1                       1101
#define IDC_LINK_BUTTON_COLOR           1102
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_BUTTON_CLASS                 32771
#define ID_BUTTON_LINK                  32772
#define ID_BUTTON_NOTE                  32773
#define ID_BUTTON_PACKAGE               32774
#define ID_BUTTON_LABEL                 32775
#define ID_BUTTON_INTERFACE             32776
#define ID_BUTTON_DISPLAY_PROPERTIES    32778
#define ID_EXPORT                       32779
#define ID_PROPERTY                     32780
#define ID_ZOOM                         32781
#define ID_ZOOM_25                      32782
#define ID_ZOOM_50                      32783
#define ID_ZOOM_100                     32784
#define ID_ZOOM_150                     32785
#define ID_ZOOM_200                     32786
#define ID_FLIP_LINK                    32787
#define ID_SHOW_GRID                    32788
#define ID_SNAP                         32789
#define ID_LINK                         32790
#define ID_IMPORT                       32791
#define ID_EDIT_DELETE                  32792
#define ID_BUTTON_TEMPLATE              32796
#define IDS_UML_CLASS                   33447
#define IDS_UML_PACKAGE                 33448
#define IDS_UML_NOTE                    33449
#define IDS_UML_LABEL                   33450
#define IDS_UML_INTERFACE               33451
#define IDS_UML_DELETE_OPERATION        33453
#define IDS_UML_DELETE_ATTRIBUTE        33454
#define IDS_UML_CLASS_MUST_HAVE_A_NAME  33455
#define IDS_UML_ATTRIBUTE_MUST_HAVE_A_NAME 33456
#define IDS_UML_OPERATION_MUST_HAVE_A_NAME 33457
#define IDS_UML_ATTRIBUTE_MUST_HAVE_A_TYPE 33458
#define IDS_UML_OPERATION_MUST_HAVE_A_TYPE 33459
#define IDS_UML_PARAMETER_MUST_HAVE_A_TYPE 33460
#define IDS_UML_PARAMETER_MUST_HAVE_A_NAME 33461
#define IDS_UML_PACKAGE_EXISTS          33463
#define IDS_UML_SELECT_FOLDER           33464
#define IDS_UML_PROPERTY_LIST_TAG_MUST_HAVE_A_VALUE 33465
#define IDS_UML_CREATEGETTERS_SETTERS   33466
#define IDS_UML_MISSING_BRACKET         33467
#define IDS_UML_MALFORMED_COMMENT       33468
#define IDS_UML_CREATECTOR_DTOR         33469
#define IDS_UML_GETTER_MUST_HAVE_A_NAME 33470
#define IDS_UML_SETTER_MUST_HAVE_A_NAME 33471
#define IDS_UML_GETSET_DEFINED          33472
#define IDS_UML_MUST_SELECT_AN_ATTRIBUTE 33473
#define ID_SETTINGS_LINKS               33478
#define ID_BUTTON3                      33479
#define ID_STREETS_FLOP                 33479
#define ID_BUTTON4                      33480
#define ID_STREETS_TURN                 33480
#define ID_SETTINGS_STREETS_PREFLOP     33482
#define ID_SETTINGS_STREETS_FLOP        33483
#define ID_SETTINGS_STREETS_TURN        33484
#define ID_SETTINGS_STREETS_RIVER       33485
#define ID_SETTINGS_ACTIONS_CHECK       33486
#define ID_SETTINGS_ACTIONS_BET         33487
#define ID_SETTINGS_ACTIONS_CALL        33488
#define ID_SETTINGS_ACTIONS_RAISE       33489
#define ID_SETTINGS_ACTIONS_FOLD        33490
#define ID_VIEW_CLASSWND                33491
#define ID_VIEW_FILEWND                 33492
#define ID_STREET_MANAGER               33494
#define ID_ACTION_MANAGER               33495
#define ID_STREETS_PREFLOP              33496
#define ID_STREETS_RIVER                33497
#define ID_ACTIONS_CHECK                33498
#define ID_ACTIONS_BET                  33499
#define ID_ACTIONS_CALL                 33500
#define ID_ACTIONS_RAISE                33501
#define ID_BUTTON10                     33502
#define ID_ACTIONS_FOLD                 33502
#define ID_EDIT_COPY                    0xE122
#define ID_EDIT_CUT                     0xE123
#define ID_EDIT_PASTE                   0xE125
#define IDS_UML_EXPORT_FINISHED         61446
#define IDS_UML_TEMPLATE                61447

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        336
#define _APS_NEXT_COMMAND_VALUE         33503
#define _APS_NEXT_CONTROL_VALUE         1098
#define _APS_NEXT_SYMED_VALUE           334
#endif
#endif
